In [2]:
from numpy import genfromtxt, zeros
# read the first 4 columns
data = genfromtxt('iris.csv',delimiter=',',usecols=(0,1,2,3))
# read the fifth column
target = genfromtxt('iris.csv',delimiter=',',usecols=(4),dtype=str)

print (data.shape)

print (target.shape)

print (set (target))

(150, 4)
(150,)
{'setosa', 'virginica', 'versicolor'}


In [3]:
t = zeros(len(target))
t[target == 'setosa'] = 1
t[target == 'versicolor'] = 2
t[target == 'virginica'] = 3

In [4]:
#from sklearn.naive_bayes import GaussianNB
#classifier = GaussianNB()
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(leaf_size=30,n_neighbors=10)


In [5]:
classifier.fit(data,t) # training on the iris dataset

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=10, p=2,
           weights='uniform')

In [10]:
from sklearn import cross_validation
train, test, t_train, t_test = cross_validation.train_test_split(data, t, test_size=0.4, random_state=0)

In [11]:
classifier.fit(train,t_train) # train
print (classifier.score(test,t_test)) # test

0.966666666667


In [12]:
from sklearn.metrics import confusion_matrix
print (confusion_matrix(classifier.predict(test),t_test))

[[16  0  0]
 [ 0 22  1]
 [ 0  1 20]]


In [13]:
from sklearn.metrics import classification_report
print (classification_report(classifier.predict(test), t_test,
target_names=['setosa', 'versicolor', 'virginica']))

             precision    recall  f1-score   support

     setosa       1.00      1.00      1.00        16
 versicolor       0.96      0.96      0.96        23
  virginica       0.95      0.95      0.95        21

avg / total       0.97      0.97      0.97        60

